version: "3.9"
services:
  rabbitmq:
    build: .
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    links:
      - "redis:redis"

#networks:
#  nacos_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.25.0.0/16

