version: "2"
services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - /Users/dengcheng/Documents/docker/mysql:/etc/mysql
      - /Users/dengcheng/Documents/docker/mysql_data/:/var/lib/mysql
    expose:
      - 3306
#    networks:
#      - default
#networks:
#  default:
#    driver: custom-driver-1
